<?php
/**
 * @var $block \Razoyo\AnimalProfile\Block\Profile\Photo
 */
?>
<p><?= $block->getGreeting() ?></p>

<div id="animalid-photo"></div>
<select name="animal" id="animal-opt">
    <option value="" selected></option> 
    <?php foreach ($block->getAnimalOpt() as $profImage): ?>
        <option value="<?= $profImage['value'] ?>" <?= $profImage['value'] == $animalProfile ? 'selected' : '' ?>>
            <?= $profImage['label'] ?>
        </option>
    <?php endforeach; ?>
</select>
<script>
    require(['jquery', 'domReady!'], function ($) {
        return $.ajax({
            url: '<?= $block->getPhotoUrl() ?>',
            type: 'GET'
        }).done(
            function (response) {
                console.log(response);
                const photoImg = document.createElement('img'); 
                photoImg.alt = 'Profile photo';
                photoImg.src = response.photo;

                const photoDiv = document.getElementById('animalid-photo');
                if (photoDiv) {
                    photoDiv.appendChild(photoImg);
                }
            }
        );
    });
</script>
